### ISSUE TITLE
Mediaan O(n) algoritme

### ISSUE THREAD

**Issue by ludopulles** [pimsp/tcr#10]
Misschien leuk om het O(n) algoritme voor het bepalen van de mediaan er in te zetten (als het niet te veel ruimte inneemt) :).

**Comment by pimsp** [comment]
https://en.cppreference.com/w/cpp/algorithm/nth_element implementeert dit al

**Comment by ludopulles** [comment]
Hmm, dat is waar. Het is niet echt O(n) maar O(n log n) maar dit zal niet uitmaken, lijkt me. Dus toch niet nuttig...
